// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PbSqlServerMonitoring.Data;

#nullable disable

namespace PbSqlServerMonitoring.Migrations
{
    [DbContext(typeof(MonitorDbContext))]
    [Migration("20260111213049_AddQueryHistoryLastExecutionTimeIndex")]
    partial class AddQueryHistoryLastExecutionTimeIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PbSqlServerMonitoring.Models.BlockingHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("BlockingSessionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLeadBlocker")
                        .HasColumnType("bit");

                    b.Property<string>("QueryText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("bigint");

                    b.Property<long>("WaitTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("WaitType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("BlockingHistory");
                });

            modelBuilder.Entity("PbSqlServerMonitoring.Models.MetricSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ActiveConnections")
                        .HasColumnType("int");

                    b.Property<int>("BlockedProcesses")
                        .HasColumnType("int");

                    b.Property<double>("BufferCacheHitRatio")
                        .HasColumnType("float");

                    b.Property<double>("CpuPercent")
                        .HasColumnType("float");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<double>("MemoryMb")
                        .HasColumnType("float");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("ServerName", "DatabaseName");

                    b.ToTable("MetricSnapshots");
                });

            modelBuilder.Entity("PbSqlServerMonitoring.Models.QueryHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("AvgCpuTimeMs")
                        .HasColumnType("float");

                    b.Property<double>("AvgElapsedTimeMs")
                        .HasColumnType("float");

                    b.Property<long>("AvgLogicalReads")
                        .HasColumnType("bigint");

                    b.Property<long>("AvgLogicalWrites")
                        .HasColumnType("bigint");

                    b.Property<string>("DatabaseName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("ExecutionCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastExecutionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("QueryHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("QueryText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LastExecutionTime");

                    b.HasIndex("SnapshotId");

                    b.ToTable("QueryHistory");
                });

            modelBuilder.Entity("PbSqlServerMonitoring.Models.BlockingHistoryEntity", b =>
                {
                    b.HasOne("PbSqlServerMonitoring.Models.MetricSnapshotEntity", "Snapshot")
                        .WithMany("BlockedQueries")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("PbSqlServerMonitoring.Models.QueryHistoryEntity", b =>
                {
                    b.HasOne("PbSqlServerMonitoring.Models.MetricSnapshotEntity", "Snapshot")
                        .WithMany("TopQueries")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("PbSqlServerMonitoring.Models.MetricSnapshotEntity", b =>
                {
                    b.Navigation("BlockedQueries");

                    b.Navigation("TopQueries");
                });
#pragma warning restore 612, 618
        }
    }
}
