version: "3.8"

services:
  sql_exporter:
    image: ghcr.io/burningalchemist/sql_exporter:latest
    container_name: sql_exporter
    ports:
      - "9399:9399"
    volumes:
      - ./sql_exporter/sql_exporter.yml:/etc/sql_exporter/sql_exporter.yml:ro
    environment:
      # Internal API key for fetching connection strings from .NET app
      - INTERNAL_API_KEY=${INTERNAL_API_KEY:-}
      # .NET app URL for fetching connection strings
      - DOTNET_APP_URL=${DOTNET_APP_URL:-http://host.containers.internal:5000}
    command:
      - "--config.file=/etc/sql_exporter/sql_exporter.yml"
    restart: unless-stopped
    networks:
      - monitoring
    extra_hosts:
      - "host.containers.internal:host-gateway"

  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alerts:/etc/prometheus/alerts:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=${PROMETHEUS_RETENTION:-15d}"
      - "--web.enable-lifecycle"
    restart: unless-stopped
    networks:
      - monitoring
    extra_hosts:
      - "host.containers.internal:host-gateway"
    depends_on:
      - sql_exporter

  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      # Allow embedding in iframes
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    restart: unless-stopped
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
